from datetime import datetime
from app import create_app, db
from app.models import Complaint

COMPLAINTS = [
    Complaint(
        session_label="Turno noche - Recepción",
        audio_filename=None,
        transcription="Buenas noches, vengo a quejarme porque anoche no pude dormir nada. El cuarto de al lado estuvo haciendo ruido hasta las 3 de la mañana, golpeando puertas y con música muy alta. Llamé a recepción dos veces y nadie contestó.",
        transcription_score=0.96,
        category="ruido",
        problem="Huésped no pudo dormir por ruido excesivo del cuarto contiguo hasta las 3 AM. Llamó a recepción dos veces sin respuesta.",
        applied_solution="ninguna",
        suggested_action="Revisar por qué la línea de recepción nocturna no fue atendida. Considerar llamada de disculpa al huésped afectado.",
        ai_cost_usd=0.0,
        status="processed",
        created_at=datetime(2026, 5, 28, 23, 42),
    ),
    Complaint(
        session_label="Turno mañana - Recepción",
        audio_filename=None,
        transcription="Buenos días. Mire, estoy muy molesto porque mi habitación no fue limpiada ayer en todo el día. Estuve fuera desde las 9 de la mañana hasta las 8 de la noche y cuando regresé la cama estaba sin tender y los baños sin limpiar. Esto no es aceptable para un hotel de esta categoría.",
        transcription_score=0.97,
        category="limpieza",
        problem="Habitación no fue limpiada en todo el día pese a que el huésped estuvo fuera más de 11 horas.",
        applied_solution="Recepcionista ofreció disculpas y envió al equipo de limpieza de inmediato.",
        suggested_action="Verificar asignación de habitaciones al turno de limpieza de ese día. Ofrecer cortesía al huésped como compensación.",
        ai_cost_usd=0.0,
        status="reviewed",
        created_at=datetime(2026, 5, 27, 8, 15),
    ),
    Complaint(
        session_label="Turno tarde - Recepción",
        audio_filename=None,
        transcription="Hola, necesito que me expliquen este cargo en mi cuenta. Aparece un consumo de minibar de 850 pesos pero yo nunca abrí el minibar, de hecho lo revisé cuando llegué y estaba vacío. No entiendo por qué me están cobrando algo que no consumí.",
        transcription_score=0.95,
        category="facturación",
        problem="Cargo incorrecto en cuenta por consumo de minibar que el huésped niega haber realizado. Afirma que el minibar estaba vacío al llegar.",
        applied_solution="Recepcionista revisó el registro y puso el cargo en disputa pendiente de verificación con housekeeping.",
        suggested_action="Corroborar con el reporte de inventario de minibar del día de entrada. Si el error es del hotel, eliminar el cargo y disculparse formalmente.",
        ai_cost_usd=0.0,
        status="processed",
        created_at=datetime(2026, 5, 29, 16, 5),
    ),
    Complaint(
        session_label="Turno mañana - Recepción",
        audio_filename=None,
        transcription="Buen día. Quiero reportar que el aire acondicionado de mi cuarto no funciona bien. Lo puse en 18 grados anoche pero el cuarto estaba sofocante, no enfriaba nada. Dormí muy mal por el calor.",
        transcription_score=0.94,
        category="temperatura",
        problem="Aire acondicionado de la habitación no enfría correctamente pese a configurarse a 18°C. El huésped pasó la noche con calor excesivo.",
        applied_solution="Se ofreció cambio de habitación al huésped.",
        suggested_action="Enviar mantenimiento a revisar la unidad de AC de la habitación antes de asignarla nuevamente.",
        ai_cost_usd=0.0,
        status="reviewed",
        created_at=datetime(2026, 5, 26, 9, 30),
    ),
    Complaint(
        session_label="Turno tarde - Recepción",
        audio_filename=None,
        transcription="Buenas tardes. Ayer pedí por teléfono que me trajeran toallas extra y almohadas adicionales a la habitación. Me dijeron que en 20 minutos llegaban y nunca llegaron. Esperé más de dos horas y al final tuve que volver a bajar yo mismo a pedirlas.",
        transcription_score=0.97,
        category="servicio_no_atendido",
        problem="Solicitud de toallas extra y almohadas adicionales no fue atendida pese a confirmar entrega en 20 minutos. El huésped esperó más de 2 horas.",
        applied_solution="Recepcionista se disculpó y entregó los artículos de forma inmediata.",
        suggested_action="Identificar qué turno recibió la solicitud y por qué no fue ejecutada. Reforzar protocolo de seguimiento de pedidos a habitaciones.",
        ai_cost_usd=0.0,
        status="processed",
        created_at=datetime(2026, 5, 29, 14, 20),
    ),
    Complaint(
        session_label="Turno noche - Recepción",
        audio_filename=None,
        transcription="Hola, tenía reservada una habitación con vista al mar, eso fue lo que pagué. Pero me dieron una habitación que da al estacionamiento. Ya hablé con alguien esta mañana y me dijeron que lo iban a solucionar pero ya son las 10 de la noche y nadie me dijo nada.",
        transcription_score=0.96,
        category="otro",
        problem="Huésped pagó habitación con vista al mar y recibió una con vista al estacionamiento. Reclamó en la mañana sin recibir respuesta o solución en todo el día.",
        applied_solution="ninguna hasta el momento del reporte nocturno.",
        suggested_action="Reasignar habitación con vista al mar con carácter urgente o aplicar compensación equivalente. Hacer seguimiento documentado de la queja inicial del turno mañana.",
        ai_cost_usd=0.0,
        status="pending",
        created_at=datetime(2026, 5, 30, 22, 10),
    ),
    Complaint(
        session_label="Turno noche - Recepción",
        audio_filename=None,
        transcription="Buenas noches, disculpe la molestia. Es que hay una fiesta o algo así en la alberca, hay mucha gente gritando y con bocinas. Mi niño no puede dormir y ya son casi las 11 de la noche. ¿Pueden hacer algo por favor?",
        transcription_score=0.95,
        category="ruido",
        problem="Ruido excesivo proveniente de la zona de alberca con música y gritos. Huésped con menor no puede dormir siendo las 23:00 hrs.",
        applied_solution="Recepcionista llamó al área de eventos para solicitar bajar el volumen.",
        suggested_action="Verificar si el evento tenía autorización y horario permitido. Reforzar política de ruido en áreas comunes después de las 22:00 hrs.",
        ai_cost_usd=0.0,
        status="processed",
        created_at=datetime(2026, 5, 25, 22, 58),
    ),
    Complaint(
        session_label="Turno mañana - Recepción",
        audio_filename=None,
        transcription="Buenos días. Encontré cucarachas en el baño de mi habitación anoche. Una salió de debajo del lavabo. Esto es inaceptable, pagué mucho dinero por este hotel y espero condiciones de higiene básicas.",
        transcription_score=0.98,
        category="limpieza",
        problem="Huésped encontró cucarachas en el baño de su habitación. Reporta presencia de plaga como inaceptable dado el precio del hotel.",
        applied_solution="Se cambió al huésped a otra habitación de inmediato y se ofreció disculpa.",
        suggested_action="Notificar al equipo de control de plagas para inspección urgente de la habitación afectada y habitaciones adyacentes.",
        ai_cost_usd=0.0,
        status="reviewed",
        created_at=datetime(2026, 5, 24, 8, 45),
    ),
    Complaint(
        session_label="Turno tarde - Recepción",
        audio_filename=None,
        transcription="Hola buenas tardes. Acabo de revisar mi estado de cuenta y veo que me cobraron dos veces la misma noche. El cargo aparece duplicado, son como 2,400 pesos en total cuando solo debería ser 1,200. Necesito que me lo corrijan.",
        transcription_score=0.97,
        category="facturación",
        problem="Cargo duplicado en la cuenta del huésped por la misma noche. Se cobró 2,400 pesos en lugar de 1,200.",
        applied_solution="Recepcionista identificó el error en el sistema y procesó el reembolso del cargo duplicado.",
        suggested_action="Revisar el sistema de facturación para identificar la causa del duplicado y prevenir que vuelva a ocurrir con otros huéspedes.",
        ai_cost_usd=0.0,
        status="reviewed",
        created_at=datetime(2026, 5, 23, 15, 30),
    ),
    Complaint(
        session_label="Turno mañana - Recepción",
        audio_filename=None,
        transcription="Buen día. El calentador de mi habitación no funciona. Me quise bañar esta mañana y el agua salió completamente fría. Llevo dos días aquí y nunca ha salido agua caliente.",
        transcription_score=0.96,
        category="temperatura",
        problem="Calentador de agua de la habitación sin funcionar. El huésped lleva dos días sin agua caliente.",
        applied_solution="Se envió a mantenimiento a revisar el calentador y se ofreció habitación alternativa mientras se resuelve.",
        suggested_action="Revisar el calentador con urgencia. Compensar al huésped por los dos días de inconveniente con agua fría.",
        ai_cost_usd=0.0,
        status="processed",
        created_at=datetime(2026, 5, 22, 9, 10),
    ),
    Complaint(
        session_label="Turno tarde - Recepción",
        audio_filename=None,
        transcription="Buenas tardes. Solicité servicio a la habitación hace más de una hora y media y todavía no llega nada. Pedí un sándwich y un jugo. Llamé de nuevo hace 30 minutos y me dijeron que ya iba pero nada.",
        transcription_score=0.95,
        category="servicio_no_atendido",
        problem="Pedido de servicio a habitación (sándwich y jugo) sin entregar después de más de 90 minutos. Segunda llamada de seguimiento sin resultado.",
        applied_solution="Recepcionista contactó directamente a cocina y confirmó envío inmediato.",
        suggested_action="Revisar el proceso de comunicación entre recepción y cocina. Establecer tiempo máximo de entrega con alerta automática si se supera.",
        ai_cost_usd=0.0,
        status="processed",
        created_at=datetime(2026, 5, 21, 13, 55),
    ),
    Complaint(
        session_label="Turno mañana - Recepción",
        audio_filename=None,
        transcription="Hola, buenos días. Quiero reportar que el elevador lleva desde ayer en la tarde fuera de servicio. Estoy en el piso 8 y tengo una lesión en la rodilla, me es muy difícil subir y bajar escaleras. Nadie me avisó de esto al momento del check-in.",
        transcription_score=0.97,
        category="otro",
        problem="Elevador fuera de servicio desde la tarde anterior. Huésped con lesión de rodilla en piso 8 no puede usar escaleras con facilidad. No fue informado al hacer check-in.",
        applied_solution="Se reasignó al huésped a una habitación en piso 2 sin costo adicional.",
        suggested_action="Actualizar protocolo de check-in para informar sobre equipos fuera de servicio. Escalar reparación del elevador como prioridad alta.",
        ai_cost_usd=0.0,
        status="reviewed",
        created_at=datetime(2026, 5, 20, 10, 5),
    ),
    Complaint(
        session_label="Turno noche - Recepción",
        audio_filename=None,
        transcription="Oiga buenas noches. Los de la habitación de arriba están corriendo o arrastrando muebles, no sé, pero el ruido es constante desde las 9 de la noche. Ya le hablé yo directamente golpeando el techo y siguieron igual.",
        transcription_score=0.94,
        category="ruido",
        problem="Ruido constante desde la habitación superior desde las 21:00 hrs. El huésped intentó comunicarse directamente sin éxito.",
        applied_solution="Recepcionista llamó a la habitación de arriba solicitando guardar silencio.",
        suggested_action="Si el ruido persiste, considerar cambio de habitación al huésped afectado. Registrar incidente para antecedentes.",
        ai_cost_usd=0.0,
        status="processed",
        created_at=datetime(2026, 5, 19, 21, 30),
    ),
    Complaint(
        session_label="Turno tarde - Recepción",
        audio_filename=None,
        transcription="Buenas tardes. El baño de mi habitación huele muy feo, como a drenaje. Abrí la ventana pero el olor persiste. Además la regadera gotea constantemente y no me deja dormir bien.",
        transcription_score=0.96,
        category="limpieza",
        problem="Baño con olor a drenaje persistente y regadera con goteo constante que afecta el descanso del huésped.",
        applied_solution="Se envió a mantenimiento para revisar la tubería y reparar la regadera.",
        suggested_action="Verificar el estado del sifón y la trampa de agua del drenaje. Documentar reparación de regadera para seguimiento.",
        ai_cost_usd=0.0,
        status="processed",
        created_at=datetime(2026, 5, 18, 16, 40),
    ),
    Complaint(
        session_label="Turno mañana - Recepción",
        audio_filename=None,
        transcription="Buenos días. Mire, en mi factura final aparece un cargo por 'estancia extendida' de 600 pesos pero yo hice el check-out a tiempo, a las 12 del día como me indicaron. No entiendo ese cargo.",
        transcription_score=0.98,
        category="facturación",
        problem="Cargo incorrecto de 600 pesos por estancia extendida en la factura final. El huésped afirma haber hecho check-out puntual al mediodía.",
        applied_solution="Se revisaron los registros del sistema y se confirmó la salida a tiempo. El cargo fue eliminado.",
        suggested_action="Revisar cómo se generó el cargo automático siendo que el check-out fue a tiempo. Evitar que el sistema aplique cargos sin confirmación manual.",
        ai_cost_usd=0.0,
        status="reviewed",
        created_at=datetime(2026, 5, 17, 12, 20),
    ),
    Complaint(
        session_label="Turno tarde - Recepción",
        audio_filename=None,
        transcription="Hola buenas tardes. La calefacción de mi habitación no enciende. Afuera está haciendo mucho frío y adentro del cuarto también. Ya intenté con el control y nada, también lo reinicié como dice el manual y tampoco funcionó.",
        transcription_score=0.95,
        category="temperatura",
        problem="Sistema de calefacción de la habitación sin funcionar. El huésped intentó reiniciarlo sin éxito.",
        applied_solution="Mantenimiento fue enviado a revisar el termostato y la unidad de calefacción.",
        suggested_action="Si no se puede reparar en menos de una hora, reubicar al huésped en habitación con calefacción operativa.",
        ai_cost_usd=0.0,
        status="processed",
        created_at=datetime(2026, 5, 16, 17, 15),
    ),
    Complaint(
        session_label="Turno noche - Recepción",
        audio_filename=None,
        transcription="Buenas noches. Solicité que me despertaran a las 6 de la mañana porque tenía un vuelo. Nunca me llamaron. Por suerte puse también alarma en mi celular si no pierdo el avión. Esto es muy grave.",
        transcription_score=0.97,
        category="servicio_no_atendido",
        problem="Solicitud de llamada despertador a las 6 AM no fue ejecutada. El huésped podría haber perdido su vuelo.",
        applied_solution="Recepcionista ofreció disculpa formal y nota de queja registrada.",
        suggested_action="Investigar quién registró la solicitud y por qué no se ejecutó. Revisar el sistema de alertas de llamadas despertador para evitar fallas.",
        ai_cost_usd=0.0,
        status="reviewed",
        created_at=datetime(2026, 5, 15, 6, 30),
    ),
    Complaint(
        session_label="Turno tarde - Recepción",
        audio_filename=None,
        transcription="Buenas tardes. Reservé una habitación doble para mí y mi esposa pero nos dieron una cama matrimonial. Somos adultos mayores y cada quien necesita su espacio para dormir bien. Queremos lo que reservamos.",
        transcription_score=0.96,
        category="otro",
        problem="Huésped reservó habitación con camas dobles y recibió una con cama matrimonial. Adultos mayores requieren camas separadas por comodidad.",
        applied_solution="Se revisó disponibilidad y se realizó cambio de habitación a una con dos camas dobles.",
        suggested_action="Verificar el proceso de asignación de habitaciones para que coincida exactamente con lo reservado, especialmente en tipo de cama.",
        ai_cost_usd=0.0,
        status="reviewed",
        created_at=datetime(2026, 5, 14, 15, 0),
    ),
    Complaint(
        session_label="Turno mañana - Recepción",
        audio_filename=None,
        transcription="Buenos días. Quiero reportar que el WiFi del hotel no funciona en mi habitación. Llevo desde ayer intentando conectarme y la señal es muy débil o directamente no conecta. Necesito trabajar desde aquí y sin internet no puedo hacer nada.",
        transcription_score=0.95,
        category="servicio_no_atendido",
        problem="El WiFi del hotel no funciona en la habitación del huésped desde el día anterior. El huésped necesita conectividad para trabajar.",
        applied_solution="Se enviaron las credenciales de una red alternativa de mayor potencia y se reportó la falla al equipo técnico.",
        suggested_action="Revisar el punto de acceso WiFi del piso correspondiente. Evaluar si la cobertura es suficiente en esa área del hotel.",
        ai_cost_usd=0.0,
        status="processed",
        created_at=datetime(2026, 5, 13, 9, 50),
    ),
]


def seed():
    app = create_app()
    with app.app_context():
        existing = Complaint.query.count()
        if existing > 0:
            print(f"La base de datos ya tiene {existing} quejas. Ejecuta con --force para reemplazarlas.")
            return

        db.session.add_all(COMPLAINTS)
        db.session.commit()
        print(f"{len(COMPLAINTS)} quejas de ejemplo insertadas correctamente.")


if __name__ == "__main__":
    import sys
    if "--force" in sys.argv:
        app = create_app()
        with app.app_context():
            Complaint.query.delete()
            db.session.commit()
            db.session.add_all(COMPLAINTS)
            db.session.commit()
            print(f"{len(COMPLAINTS)} quejas insertadas (base de datos limpiada previamente).")
    else:
        seed()
